name: Pull Request Labeler
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Label Pull Requests
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
